import { createRequire } from 'node:module'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { mkdir } from 'node:fs/promises'

const require = createRequire(new URL('../../frontend/package.json', import.meta.url))
const { expect, test } = require('@playwright/test')

const fixture = path.join(path.dirname(fileURLToPath(import.meta.url)), 'fixtures', 'product.md')
const screenshots = path.join(path.dirname(fileURLToPath(import.meta.url)), '../../output/playwright')

test('登录、知识库、多轮聊天、回收站与登出完整流程', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.goto('/login')
  await mkdir(screenshots, { recursive: true })
  await page.screenshot({ path: path.join(screenshots, 'login-portfolio.png'), fullPage: true })
  await page.getByLabel('用户名').fill('king')
  await page.getByLabel('密码').fill('Local-QA-Password-2026')
  await page.getByRole('button', { name: '进入运营台' }).click()
  await expect(page).toHaveURL(/\/chat$/)
  await expect(page.getByLabel('选择对话模型')).toHaveValue('e2e-fast')
  await page.getByLabel('选择对话模型').selectOption('e2e-accurate')

  await page.getByLabel('输入问题').fill('今天出了几单')
  await page.getByRole('button', { name: '发送' }).click()
  await expect(page.getByText('订单汇总 ✓')).toBeVisible()
  await expect(page.getByText(/订单概况：342 单/)).toBeVisible()
  await expect(page.getByText('演示数据')).toBeVisible()

  await page.getByRole('link', { name: '知识库' }).click()
  const chooser = page.waitForEvent('filechooser')
  await page.getByRole('button', { name: '上传文档' }).click()
  await (await chooser).setFiles(fixture)
  await expect(page.getByText('product.md 已安全索引')).toBeVisible()
  await page.getByRole('button', { name: /product\.md 1 个分片/ }).click()
  await expect(page.getByText(/24 小时保冷/)).toBeVisible()
  await page.screenshot({ path: path.join(screenshots, 'knowledge-portfolio.png'), fullPage: true })

  await page.getByRole('button', { name: '新建对话', exact: true }).click()
  await page.getByLabel('输入问题').fill('Aurora 保温杯适合哪类客户？')
  await page.getByRole('button', { name: '发送' }).click()
  await expect(page.getByText(/当前会话包含 0 条历史消息/)).toBeVisible()
  await page.getByLabel('输入问题').fill('它的核心卖点是什么？')
  await page.getByRole('button', { name: '发送' }).click()
  await expect(page.getByText(/当前会话包含 2 条历史消息/)).toBeVisible()

  await page.getByRole('link', { name: '知识库' }).click()
  page.once('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: '移入回收站' }).click()
  await expect(page.getByText('文档已移入回收站')).toBeVisible()
  await page.getByRole('button', { name: '回收站' }).click()
  await page.getByRole('button', { name: '恢复' }).click()
  await expect(page.getByText('文档已恢复并重新索引')).toBeVisible()

  await page.getByRole('link', { name: '设置' }).click()
  await expect(page.getByRole('heading', { name: '设置与连接' })).toBeVisible()
  await expect(page.getByRole('button', { name: '刷新' })).toBeEnabled({ timeout: 15_000 })
  await page.screenshot({ path: path.join(screenshots, 'settings-portfolio.png'), fullPage: true })
  await page.getByRole('button', { name: '退出登录' }).click()
  await expect(page).toHaveURL(/\/login$/)
})

test('深度分析真实循环事件、模型传递、历史恢复与响应式布局', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.goto('/login')
  await page.getByLabel('用户名').fill('king')
  await page.getByLabel('密码').fill('Local-QA-Password-2026')
  await page.getByRole('button', { name: '进入运营台' }).click()
  await page.getByRole('button', { name: '新建对话', exact: true }).click()
  await page.getByLabel('选择对话模型').selectOption('e2e-accurate')
  await page.getByRole('button', { name: '深度分析', exact: true }).click()
  await page.getByLabel('输入问题').fill('分析最近7天的经营情况')
  await page.getByRole('button', { name: '发送', exact: true }).click()
  await expect(page.getByText('初始计划')).toBeVisible()
  await expect(page.getByRole('heading', { name: '深度分析测试报告' })).toBeVisible()
  await expect(page.getByText('深度分析 · 分析已完成')).toBeVisible()
  await expect(page.getByText('使用模型：e2e-accurate。')).toBeVisible()
  await page.reload()
  await expect(page.getByRole('heading', { name: '深度分析测试报告' })).toBeVisible()
  await page.locator('.analysis-trace summary').click()
  await expect(page.getByText('重规划 · 第 1 次调整')).toBeVisible()
  await expect(page.getByText('步骤 2 · 补充产品表现核查')).toBeVisible()
  await mkdir(screenshots, { recursive: true })
  await page.screenshot({ path: path.join(screenshots, 'deep-analysis-desktop.png'), fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  await expect(page.getByRole('button', { name: '深度分析', exact: true })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({ path: path.join(screenshots, 'deep-analysis-mobile.png'), fullPage: true })
  await page.locator('.conversation').evaluate(element => { element.scrollTop = element.scrollHeight })
  await page.screenshot({ path: path.join(screenshots, 'deep-analysis-mobile-report.png'), fullPage: true })
})

test('深度分析停止会取消后台流并保存中断状态', async ({ page }) => {
  await page.goto('/login')
  await page.getByLabel('用户名').fill('king')
  await page.getByLabel('密码').fill('Local-QA-Password-2026')
  await page.getByRole('button', { name: '进入运营台' }).click()
  await page.getByRole('button', { name: '新建对话', exact: true }).click()
  await page.getByRole('button', { name: '深度分析', exact: true }).click()
  await page.getByLabel('输入问题').fill('停止测试：分析订单')
  await page.getByRole('button', { name: '发送', exact: true }).click()
  await expect(page.getByText('初始计划')).toBeVisible()
  await page.getByRole('button', { name: '停止生成' }).click()
  await expect(page.getByText('深度分析 · 分析已中断')).toBeVisible()
  await expect.poll(async () => {
    const list = await (await page.request.get('/api/chat/sessions')).json()
    const detail = await (await page.request.get(`/api/chat/sessions/${list.items[0].id}`)).json()
    return detail.messages.at(-1)?.status
  }).toBe('interrupted')
  await page.reload()
  await expect(page.getByText('深度分析 · 分析已中断')).toBeVisible()
  await expect(page.getByRole('button', { name: '重试', exact: true })).toBeVisible()
})
